### ISSUE TITLE
Move to Zimbra organisation?

### ISSUE THREAD

**Issue by danchr** [plobbes/vagrant-provision-zimbra#11]
Wouldn't it make more sense to have this repository in the @Zimbra organisation? That'd make it a bit more official-seeming and easier for other people to contribute to 😊

**Comment by jorgedlcruz** [comment]
+1

**Comment by quanah** [comment]
Yeah, likely at this point it would be.

**Comment by plobbes** [comment]
I just transferred this over to the zimbra org.  Looks like I may need to update the license slightly too, but you should now update your remote url to point to the new location.
